# Generated by Django 5.2.8 on 2025-11-18 11:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_cart_items_alter_cart_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
