# Generated by Django 5.2.8 on 2025-11-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_remove_restaurant_cuisine_alter_item_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique name for the image. Example: login_bg, login_logo', max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='site_images/')),
            ],
        ),
    ]
