# Makefile for Meal Buddy project

.PHONY: run migrate

run:
	python manage.py runserver

migrate:
	python manage.py makemigrations
	python manage.py migrate

createsuperuser:
	python manage.py createsuperuser

install:
	pip install -r requirements.txt
